### ISSUE TITLE
Is your clcn-app/.babelrc all good?

### ISSUE THREAD

**Issue by ghost** [JsChannel-Community/rxjs-workshop-nov-2015#1]
When i run npm start, it throws error as,

``` javascript
[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./server.js`

/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:102
      throw err;
            ^
SyntaxError: /home/sk/ws/rxjs-workshop-nov-2015/clcn-app/.babelrc: Unexpected token p
    at Object.parse (native)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:98:62)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:228:10)
    at compile (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by bitspook** [comment]
Looks like your `clcn_app/.babelrc` have invalid json. Cal you please put here what’s in your .clcn_app/.babelrc? For me it's working well. Also note that you need to update your globally installed babel to babel 6. a simple `npm i -g babel-cli` shall do.

**Comment by bitspook** [comment]
I double checked it with a fresh clone. If you haven't changed the babelrc, I think it's a problem with your globally installed babel. Probably remove it and install `babel-cli`.

**Comment by ghost** [comment]
my babel is versioned 5.8.3. To move to babel 6, i need to change node binary from 0.10 to 0.12... i feel, upgrading my nodejs binary is suicidal!!!

**Comment by bitspook** [comment]
Well, you should use a node version management system anyway. Try `n`(https://github.com/tj/n). I've been using it without any problems since forever. It'll allow you to switch b/w node binaries when you see fit. Install latest node (5.0.0) instead. I guess I should've put an engines field in the package.json

**Comment by ghost** [comment]
I am getting these warnings, when i did npm -g uninstall babel-cli && npm -g i babel-cli,

``` javascript
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN engine hawk@3.1.1: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine get-stdin@5.0.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
```

But surprisingly, npm start worked even with those warns....
one need not change his node binary... just upgrading babel to 6+ is sufficient...

**Comment by bitspook** [comment]
Sounds good. Check the `localhost:8000/promise.html` if you're seeing a message in console. If you do, babel is working well.

**Comment by ghost** [comment]
the one word log is there

**Comment by bitspook** [comment]
Cool.

In this app we simply convert `clcn_app/promise.js` and `clcn_app/observable.js` from ES6 to ES5 and send to browser. A single line log is all there is in them (I put it there for testing ES6->ES5 conversion). We'll work in these files in the workshop.

**Comment by ghost** [comment]
In recene/package.json, @ln6, change bable to babel

**Comment by bitspook** [comment]
Lol. Just did. We don't really use build in this app though, so it was good either way. We'll directly use `babel-node` instead of building it every time.

**Comment by ghost** [comment]
even i never did.. i ran `npm install` and after sometime, i see it shows me it is running, `npm run build`.. don't know, what triggered it?

**Comment by bitspook** [comment]
the prepublish script in npm.

---

Charanjit Singh
Github https://github.com/channikhabra || Twitter https://twitter.com/channikhabra || +91-7696166158

**Comment by ghost** [comment]
still it fails at this cmd, `babel -d ./src ./dist`, saying `dist` dir doesn't exist. i removed it by hacking to create a dir `dist`  and then ran `babel -d ./src  ./dist`. Now, i thought compiled parser.js will be inside dist folder but dist dir is empty...

**Comment by bitspook** [comment]
Honestly man, I put that build script in there just by habit. I think I shall remove it. Let me remove it and check it. Will get back to you in a minute.

**Comment by bitspook** [comment]
Please pull new changes and try again. `cd ./recene/tests/dummy_site/` and `babel-node ../../src/index.js` to check it's working all well.

Sorry for all the trouble man, and thanks for trying it out before the workshop. These silly things take all the time in workshops.

**Comment by ghost** [comment]
it runs, and i can see the shit log....
