### ISSUE TITLE
Add a screenshot for recene app

### ISSUE THREAD

**Issue by ghost** [JsChannel-Community/rxjs-workshop-nov-2015#3]
Really no clues what, recene app does at the end?
can you put a screenshot of its final look in the readme.md page?

**Comment by bitspook** [comment]
It's a [static-site generator](https://jekyllrb.com/).
- Checkout to the devel branch
- cd to recene/tests/dummy_site
- run `babel-node ../../src/index.js`

It will create `_public` directory, which is markdown posts in `_posts` directory converted to HTML and theme in `recene/src/theme` applied to them. It would look like this:

<img width="1440" alt="screen shot 2015-11-20 at 5 44 05 pm" src="https://cloud.githubusercontent.com/assets/1437091/11299645/73f322f6-8fae-11e5-9e7e-abe83b7b629c.png">
