### ISSUE TITLE
Transpile public js files from ES2015 to ES5

### ISSUE THREAD

**Issue by samarpanda** [JsChannel-Community/rxjs-workshop-nov-2015#4]
Build tasks to transpile public js files from ES2015 to ES5 using babel. Although its not important for existing project. Would be required before adding static files to CDN.

**Comment by bitspook** [comment]
Assuming you are talking about clcn_app, files in public dir don't really need to be converted. They're just libraries which are already built. Only files we change (hence need to be built) and write ES6 in are `clcn_app/promise.js` and `clcn_app/observable.js`, which are built by the `./server.js` on the fly. 

So I guess we're good without building public js files.

I am closing the issue. Please reopen if I have misunderstood you.
