### ISSUE TITLE
Double underscores in css classes

### ISSUE THREAD

**Issue by ghost** [JsChannel-Community/rxjs-workshop-nov-2015#5]
In rxjs-workshop-nov-2015/recene/src/theme/css/main.css, i am seeing you are using double underscores instead of hypens (mostly,  i had come across in the past) to seperate words.

Is this css file - main.css part of some standard library (or) your custom lib?

**Comment by bitspook** [comment]
I copied that css from some random jekyll theme to quickly pull everything together. FYI That css is using BEM notation.
