### ISSUE TITLE
Recene parser, yaml/content regex 

### ISSUE THREAD

**Issue by ghost** [JsChannel-Community/rxjs-workshop-nov-2015#6]
I see this regex,
`/^(-{3}(?:\n|\r)([\w\W]+?)(?:\n|\r)-{3})?([\w\W]*)*/`
that is used to extract the yaml block and the markdown content.

There are two capturing pattern,  `(-{3}(?:\n|\r)([\w\W]+?)(?:\n|\r)-{3})` for the yaml string and `([\w\W]*)` for the markdown string.

why do we need `*` after the second pattern `([\w\W]*)`, since the pattern inside paren matches all the remaining content?

**Comment by bitspook** [comment]
I didn't put that much thought in here. It was a rxjs workshop, and I prepared it on very tight schedule. Here's the actual code I used for parsing front-matter: https://github.com/dworthen/js-yaml-front-matter/blob/master/lib/js-yaml-front.js#L7
